config/routes.rb
Quasar::Application.routes.draw do

  devise_for :users
  
  resources :posts
  
  root         :to => 'pages#home'
  
  match '/about'   => 'pages#about'
  match '/contact' => 'pages#contact'
  match '/help'    => 'pages#help'
  match '/terms'   => 'pages#terms'
  match '/privacy' => 'pages#privacy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user

  default_scope :order => 'microposts.created_at DESC'
  
  validates :user_id, :presence => true
  validates :content, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  has_many :posts, :dependent => :destroy
  
  validates :name, { :presence   => true,
                     :uniqueness => true,
                     :length     => 3..20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "home"
  end

  def about
    @title = "about"
  end

  def contact
    @title = "contact"
  end

  def help
    @title = "help"
  end

  def terms
    @title = "terms"
  end

  def privacy
    @title = "privacy"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_filter :authenticate_user!
  
  def new
    @title = "new post"
    @post = Post.new
  end

  def show
  end

  def edit
  end

  def destroy
  end

  def create
    @post = current_user.posts.build(params[:post])
    if @post.save
      flash[:notice] = "Post Created"
      redirect_to root_path
    else
      render 'posts/new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "Quasar"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title.capitalize}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class = "span-24">
    [ <%= link_to "About",   about_path   %> |
      <%= link_to "Contact", contact_path %> |
      <%= link_to "Help",    help_path    %> |
      <%= link_to "Terms",   terms_path   %> |
      <%= link_to "Privacy", privacy_path %> ]

    <br />
    
    <div class = "small">2011 &copy; Quasar</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  
  <div class = "prepend-3 span-15">
    <%= link_to "Home", root_path %>
  </div>
  
  <div class = "span-6 last">
    <%= render 'layouts/user_bar' %>
  </div>
  
  <%# Spacer row %>
  <div class = "span-24 last">
    &nbsp;
  </div>
  
  <%# Flash message row %>
  <div class = "prepend-3 span-15 append-6 last">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, :class => "flash #{key}") %>
    <% end %>
  </div>

</header>

app/views/layouts/_js.html.erb
<%= javascript_include_tag :defaults %>

app/views/layouts/_style.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => "screen" %>
<%= stylesheet_link_tag 'custom' %>
<%= stylesheet_link_tag 'js' %>

app/views/layouts/_user_bar.html.erb
<div class = "user_bar">
  
  <% if user_signed_in? %>
    [ <%= current_user.name %> ] <br />
    [ <%= link_to "Settings", edit_user_registration_path %> |
    <%= link_to "Sign Out", destroy_user_session_path   %> ]
  <% else %>
      [ <%= link_to "Sign Up", new_user_registration_path %>
       or 
      <%= link_to "Sign In", new_user_session_path %> ]
  <% end %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/style' %>
  <%= render 'layouts/js' %>
  <%= csrf_meta_tag %>
</head>
<body><div class = "container">

  <%= render 'layouts/header' %>
  
  <div class = "span-3">
    &nbsp;
  </div>
  
  <div class = "span-15">
    <%= yield %>
  </div>
  
  <div class = "span-6 last">
    &nbsp;
  </div>

  <%= render 'layouts/footer' %>

</div></body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<div class = "slider_button">
  SLIDE!
</div>

<div class = "slider">
  OMG A SLIDER
</div>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/new.html.erb
<% form_for(@post) do |f| %>
  <%= render 'shared/post_error_messages' %>
  
  <p><%= f.label :content, "Post" %><br />
  <%= f.text_area :content %></p>
  
  <%= f.submit "Post" %>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/shared/_post_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> 
        need to be fixed in order to successfully create post:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>